name: nectarchain-dirac
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8 # nail the python version, so conda does not try upgrading / downgrading
  - ctapipe=0.12
  - numpy=1.22 # higher versions >=1.23 don't work due to astropy4 dependency in ctapipe0.12
  - jupyterlab
  - protozfits=2.0
  - pytest-runner
  - pip
  - pip:
      - git+https://github.com/cta-observatory/ctapipe_io_nectarcam.git
      - CTADIRAC
      - COMDIRAC
  - dirac-grid<8  # required by DIRAC
